# Generated by Django 4.0.6 on 2023-02-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iou_tracker', '0002_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.JSONField(default=dict),
        ),
    ]
